// Auto-generated from rasabjunior portfolio source (user owns full copyright).
export type FullCategory = 'fashion' | 'beauty' | 'jewelry' | 'watches' | 'food' | 'furniture' | 'photography' | 'wedding' | 'healthcare' | 'hair' | 'education';

export type FullProject = {
  category: FullCategory;
  image: string;
  alt: string;
  title: string;
  desc: string;
  orderedBy: string;
};

export const featuredShowcase: string[] = [
  "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609488/IMG-20250921-WA0084_wa8sbj.jpg",
  "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609494/IMG-20250921-WA0085_r0wxvo.jpg",
  "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609495/IMG-20250921-WA0087_vuocad.jpg",
  "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609495/IMG-20250921-WA0088_kardpv.jpg",
];

export const fullProjects: FullProject[] = [
  {
    category: "furniture",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609496/IMG-20250921-WA0089_xhiy3t.jpg",
    alt: "Luxury Furniture Collection",
    title: "Elegant Home Living",
    desc: "Premium Furniture & Home Decor",
    orderedBy: "home_stylist_elite",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609476/IMG-20250921-WA0079_odyztd.jpg",
    alt: "Laser Hair Removal Device",
    title: "SmoothSkin Pro",
    desc: "Advanced At-Home Hair Removal",
    orderedBy: "skin_care_innovator",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609479/IMG-20250921-WA0080_mpyull.jpg",
    alt: "Contemporary Fashion Collection",
    title: "Urban Style Collective",
    desc: "Trendsetting Apparel & Accessories",
    orderedBy: "fashion_forward_23",
  },
  {
    category: "jewelry",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609484/IMG-20250921-WA0081_xj5aud.jpg",
    alt: "Exquisite Jewelry Collection",
    title: "Gilded Treasures",
    desc: "Handcrafted Fine Jewelry",
    orderedBy: "sparkle_and_shine_co",
  },
  {
    category: "watches",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609485/IMG-20250921-WA0082_lco1hc.jpg",
    alt: "Luxury Timepiece Collection",
    title: "Timeless Elegance",
    desc: "Premium Watch Collection",
    orderedBy: "watch_enthusiast_88",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609486/IMG-20250921-WA0083_o3a777.jpg",
    alt: "Artisan Bakery Products",
    title: "Golden Crust Bakery",
    desc: "Fresh Bread & Pastries Daily",
    orderedBy: "baking_artisan_co",
  },
  {
    category: "healthcare",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609467/IMG-20250921-WA0073_mmzmw8.jpg",
    alt: "Healthcare & Education Services",
    title: "Wellness & Learning Hub",
    desc: "Integrated Health & Education Services",
    orderedBy: "community_care_network",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609467/IMG-20250921-WA0074_kvcopb.jpg",
    alt: "Makeup & Cosmetics Collection",
    title: "Glamour Palette",
    desc: "Professional Makeup Studio",
    orderedBy: "makeup_maestro_art",
  },
  {
    category: "watches",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609469/IMG-20250921-WA0075_nqp3sx.jpg",
    alt: "Premium Watch Collection",
    title: "Precision Timekeepers",
    desc: "Luxury Watch Boutique",
    orderedBy: "timepiece_connoisseur",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609475/IMG-20250921-WA0076_xlzml9.jpg",
    alt: "Comfortable Loungewear Collection",
    title: "Cozy Comfort Wear",
    desc: "Premium Loungewear Collection",
    orderedBy: "comfort_lifestyle_co",
  },
  {
    category: "furniture",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609475/IMG-20250921-WA0077_p04ox5.jpg",
    alt: "Home Decor & Accessories",
    title: "Home Harmony",
    desc: "Furniture & Home Accessories",
    orderedBy: "interior_design_pro",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609456/IMG-20250921-WA0068_asizxc.jpg",
    alt: "Women's Fashion Collection",
    title: "Elegance Defined",
    desc: "Women's Fashion & Dresses",
    orderedBy: "style_curator_ella",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609457/IMG-20250921-WA0069_iipeyp.jpg",
    alt: "Beauty & Skincare Products",
    title: "Radiant Beauty",
    desc: "Premium Beauty Collection",
    orderedBy: "glow_aesthetics_co",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609457/IMG-20250921-WA0070_s15bju.jpg",
    alt: "Skincare Products Collection",
    title: "Skin Revival",
    desc: "Advanced Skincare Solutions",
    orderedBy: "dermatology_specialist",
  },
  {
    category: "photography",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609458/IMG-20250921-WA0071_utlrrb.jpg",
    alt: "Professional Photography Services",
    title: "Frame Perfect Photography",
    desc: "Professional Photo Studio",
    orderedBy: "lens_master_pro",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609466/IMG-20250921-WA0072_rosja2.jpg",
    alt: "Fashion Model Portfolio",
    title: "Model Portfolio Pro",
    desc: "Professional Modeling Showcase",
    orderedBy: "model_management_elite",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609446/IMG-20250921-WA0063_n9ina9.jpg",
    alt: "Beauty & Skincare Products",
    title: "Pure Glow Essentials",
    desc: "Beauty & Skincare Collection",
    orderedBy: "skin_care_specialist",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609447/IMG-20250921-WA0064_favzad.jpg",
    alt: "Hair Care Routine Products",
    title: "Hair Revival System",
    desc: "Complete Hair Care Routine",
    orderedBy: "hair_expert_studio",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609447/IMG-20250921-WA0066_fx6zvo.jpg",
    alt: "Hair Styling Services",
    title: "StyleCraft Hair Studio",
    desc: "Professional Hairdressing Services",
    orderedBy: "master_stylist_co",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609448/IMG-20250921-WA0065_hrogzu.jpg",
    alt: "Fresh Baked Bread Products",
    title: "Artisan Bread Haven",
    desc: "Freshly Baked Bread Daily",
    orderedBy: "baker_craft_master",
  },
  {
    category: "watches",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609455/IMG-20250921-WA0067_feqvr9.jpg",
    alt: "Luxury Watch Collection",
    title: "Timepiece Elegance",
    desc: "Premium Wristwatch Collection",
    orderedBy: "watch_collector_elite",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609429/IMG-20250921-WA0056_lwbf74.jpg",
    alt: "Activewear Collection",
    title: "ElanWear Active",
    desc: "Performance Activewear Brand",
    orderedBy: "active_lifestyle_co",
  },
  {
    category: "photography",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609429/IMG-20250921-WA0057_rlf6ji.jpg",
    alt: "Wedding Photography Services",
    title: "Eternal Moments Photography",
    desc: "Wedding & Special Events",
    orderedBy: "wedding_photographer_pro",
  },
  {
    category: "healthcare",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609432/IMG-20250921-WA0058_yhjjbq.jpg",
    alt: "Healthcare Services",
    title: "Vitality Healthcare",
    desc: "Comprehensive Medical Services",
    orderedBy: "health_wellness_group",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609437/IMG-20250921-WA0059_jb4hjr.jpg",
    alt: "Chocolate & Confectionery",
    title: "Decadent Delights",
    desc: "Artisan Chocolate Collection",
    orderedBy: "chocolate_connoisseur",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609438/IMG-20250921-WA0060_uegleg.jpg",
    alt: "Women's Fashion Collection",
    title: "Feminine Elegance",
    desc: "Women's Wear Collection",
    orderedBy: "style_curator_ella",
  },
  {
    category: "jewelry",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609418/IMG-20250921-WA0051_trgfmv.jpg",
    alt: "Fine Jewelry Collection",
    title: "Sparkle & Shine",
    desc: "Rings, Bangles & Necklaces",
    orderedBy: "jewelry_design_house",
  },
  {
    category: "jewelry",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609422/IMG-20250921-WA0052_aeyhws.jpg",
    alt: "Luxury Jewelry Collection",
    title: "Gemstone Elegance",
    desc: "Premium Jewelry Collection",
    orderedBy: "luxury_gems_direct",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609422/IMG-20250921-WA0053_pyyn9d.jpg",
    alt: "Hair Wig Collection",
    title: "Wig Couture",
    desc: "Premium Wig Collection",
    orderedBy: "hair_transformation_co",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609423/IMG-20250921-WA0054_na1zyp.jpg",
    alt: "Women's Wig Collection",
    title: "Femme Wig Boutique",
    desc: "Women's Wig Specialists",
    orderedBy: "wig_stylist_elite",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609428/IMG-20250921-WA0055_bihrmh.jpg",
    alt: "Hair Care Products",
    title: "Hair Revival Shampoo",
    desc: "Professional Hair Care Solutions",
    orderedBy: "hair_care_laboratory",
  },
  {
    category: "education",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609403/IMG-20250921-WA0041_j6rrds.jpg",
    alt: "Educational Services",
    title: "Academic Excellence Hub",
    desc: "School Admission Services",
    orderedBy: "education_consultant_pro",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609409/IMG-20250921-WA0045_fmchvc.jpg",
    alt: "Chocolate Collection",
    title: "Cocoa Delights",
    desc: "Premium Chocolate Collection",
    orderedBy: "chocolate_artisan_co",
  },
  {
    category: "healthcare",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609410/IMG-20250921-WA0047_as8q55.jpg",
    alt: "Nutritional Therapy Services",
    title: "Nutritional Wellness",
    desc: "Therapeutic Nutrition Services",
    orderedBy: "nutrition_therapy_expert",
  },
  {
    category: "furniture",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609410/IMG-20250921-WA0048_g7xsu1.jpg",
    alt: "Home Decor Collection",
    title: "Home Style Sanctuary",
    desc: "Interior Decor & Accessories",
    orderedBy: "home_decor_specialist",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609412/IMG-20250921-WA0049_mour35.jpg",
    alt: "Bakery Products",
    title: "Sweet Treats Bakery",
    desc: "Bagels, Doughnuts & More",
    orderedBy: "bakery_delights_co",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
    alt: "Model Fashion Wear",
    title: "Model Wear Collection",
    desc: "Professional Modeling Attire",
    orderedBy: "model_fashion_house",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609396/IMG-20250921-WA0037_w7p61m.jpg",
    alt: "Comfortable Women's Wear",
    title: "Comfort Couture",
    desc: "Comfy Wears for Women",
    orderedBy: "comfort_fashion_co",
  },
  {
    category: "watches",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609397/IMG-20250921-WA0038_rhhbbb.jpg",
    alt: "Wedding Planning Services",
    title: "Dream Wristwatch",
    desc: "Complete Wristwatches Coordination",
    orderedBy: "wwatch_coordinator_pro",
  },
  {
    category: "wedding",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0039_htnlsc.jpg",
    alt: "Catering Services",
    title: "Gourmet Event Catering",
    desc: "Premium Catering for Events",
    orderedBy: "event_catering_expert",
  },
  {
    category: "watches",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0040_trxzvg.jpg",
    alt: "Luxury Watch Collection",
    title: "Chronograph Masters",
    desc: "Premium Wristwatch Collection",
    orderedBy: "watch_aficionado_co",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
    alt: "Doughnut Shop",
    title: "Doughnut Delights",
    desc: "Artisan Doughnut Creations",
    orderedBy: "doughnut_artisan_co",
  },
  {
    category: "beauty",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0031_v4z4og.jpg",
    alt: "Makeup Collection",
    title: "Makeup Artistry Pro",
    desc: "Professional Makeup Collection",
    orderedBy: "makeup_artist_elite",
  },
  {
    category: "hair",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609388/IMG-20250921-WA0032_wsumfr.jpg",
    alt: "Wig Shop",
    title: "Wig Emporium",
    desc: "Premium Wig Shop",
    orderedBy: "wig_boutique_direct",
  },
  {
    category: "healthcare",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0035_el4z5x.jpg",
    alt: "Nutritionist Services",
    title: "Nutritional Balance",
    desc: "Professional Nutritionist Services",
    orderedBy: "nutrition_expert_co",
  },
  {
    category: "fashion",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
    alt: "Women's Wear Collection",
    title: "Women's Fashion Hub",
    desc: "Contemporary Women's Wear",
    orderedBy: "fashion_design_studio",
  },
  {
    category: "food",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609391/IMG-20250921-WA0034_ororfg.jpg",
    alt: "Treats & Confectionery",
    title: "Celebration Treats",
    desc: "Treats for Any Occasion",
    orderedBy: "sweet_celebrations_co",
  },
  {
    category: "photography",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0027_gf1wfr.jpg",
    alt: "Photography Services",
    title: "Creative Lens Photography",
    desc: "Professional Photography Studio",
    orderedBy: "photo_artist_collective",
  },
  {
    category: "photography",
    image: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
    alt: "Wedding Photography Services",
    title: "Memorable Moments Photography",
    desc: "Wedding & Event Photography",
    orderedBy: "wedding_photography_pro",
  },
];

export const filterCategories: { value: FullCategory | 'all'; label: string }[] = [
  { value: "all", label: "All Projects" },
  { value: "fashion", label: "Fashion" },
  { value: "beauty", label: "Beauty" },
  { value: "jewelry", label: "Jewelry" },
  { value: "watches", label: "Watches" },
  { value: "food", label: "Food & Bakery" },
  { value: "furniture", label: "Furniture" },
  { value: "photography", label: "Photography" },
  { value: "wedding", label: "Wedding" },
  { value: "healthcare", label: "Healthcare" },
  { value: "hair", label: "Hair Care" },
  { value: "education", label: "Education" },
];
