/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FullReviewsRouteImport } from './routes/full-reviews'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioFullRouteImport } from './routes/portfolio.full'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FullReviewsRoute = FullReviewsRouteImport.update({
  id: '/full-reviews',
  path: '/full-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioFullRoute = PortfolioFullRouteImport.update({
  id: '/full',
  path: '/full',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/full-reviews': typeof FullReviewsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/portfolio/full': typeof PortfolioFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/full-reviews': typeof FullReviewsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/portfolio/full': typeof PortfolioFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/full-reviews': typeof FullReviewsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/portfolio/full': typeof PortfolioFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/full-reviews'
    | '/portfolio'
    | '/reviews'
    | '/services'
    | '/portfolio/full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/full-reviews'
    | '/portfolio'
    | '/reviews'
    | '/services'
    | '/portfolio/full'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/full-reviews'
    | '/portfolio'
    | '/reviews'
    | '/services'
    | '/portfolio/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FullReviewsRoute: typeof FullReviewsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-reviews': {
      id: '/full-reviews'
      path: '/full-reviews'
      fullPath: '/full-reviews'
      preLoaderRoute: typeof FullReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/full': {
      id: '/portfolio/full'
      path: '/full'
      fullPath: '/portfolio/full'
      preLoaderRoute: typeof PortfolioFullRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioFullRoute: typeof PortfolioFullRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioFullRoute: PortfolioFullRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FullReviewsRoute: FullReviewsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
